// <auto-generated />
using MVC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MVC.Migrations
{
    [DbContext(typeof(ShopDbContext))]
    [Migration("20241125231718_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MVC.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TenDanhMuc")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("DanhMucs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TenDanhMuc = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            TenDanhMuc = "Điện Thoại"
                        },
                        new
                        {
                            Id = 3,
                            TenDanhMuc = "Đồng Hồ Thông Minh"
                        },
                        new
                        {
                            Id = 4,
                            TenDanhMuc = "Tai Nghe"
                        },
                        new
                        {
                            Id = 5,
                            TenDanhMuc = "Máy Ảnh"
                        },
                        new
                        {
                            Id = 6,
                            TenDanhMuc = "Tivi"
                        });
                });

            modelBuilder.Entity("MVC.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TenSP")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryID");

                    b.ToTable("SanPhams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryID = 1,
                            Gia = 20000000m,
                            HinhAnh = "dell-inspiron.jpg",
                            MoTa = "Laptop Dell hiệu suất cao, phù hợp cho công việc.",
                            Slug = "laptop-dell-inspiron",
                            TenSP = "Laptop Dell Inspiron"
                        },
                        new
                        {
                            Id = 2,
                            CategoryID = 2,
                            Gia = 25000000m,
                            HinhAnh = "iphone-14.jpg",
                            MoTa = "iPhone 14 với công nghệ camera tiên tiến.",
                            Slug = "dien-thoai-iphone-14",
                            TenSP = "Điện Thoại iPhone 14"
                        },
                        new
                        {
                            Id = 3,
                            CategoryID = 3,
                            Gia = 6000000m,
                            HinhAnh = "galaxy-watch.jpg",
                            MoTa = "Đồng hồ thông minh với các tính năng sức khỏe.",
                            Slug = "smartwatch-samsung-galaxy-watch",
                            TenSP = "Smartwatch Samsung Galaxy Watch"
                        },
                        new
                        {
                            Id = 4,
                            CategoryID = 4,
                            Gia = 8500000m,
                            HinhAnh = "sony-wh-1000xm5.jpg",
                            MoTa = "Tai nghe chống ồn cao cấp từ Sony.",
                            Slug = "tai-nghe-sony-wh-1000xm5",
                            TenSP = "Tai Nghe Sony WH-1000XM5"
                        },
                        new
                        {
                            Id = 5,
                            CategoryID = 5,
                            Gia = 32000000m,
                            HinhAnh = "canon-eos-r10.jpg",
                            MoTa = "Máy ảnh mirrorless nhỏ gọn, chất lượng cao.",
                            Slug = "may-anh-canon-eos-r10",
                            TenSP = "Máy Ảnh Canon EOS R10"
                        },
                        new
                        {
                            Id = 6,
                            CategoryID = 6,
                            Gia = 45000000m,
                            HinhAnh = "lg-oled-c3.jpg",
                            MoTa = "Tivi OLED với công nghệ hình ảnh vượt trội.",
                            Slug = "tivi-lg-oled-c3",
                            TenSP = "Tivi LG OLED C3"
                        });
                });

            modelBuilder.Entity("MVC.Models.Product", b =>
                {
                    b.HasOne("MVC.Models.Category", "Category")
                        .WithMany("Categories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("MVC.Models.Category", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
